version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://mysql:password@db:3306/lcm_analytics
      - NEXTAUTH_SECRET=your-secret-key-here
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=lcm_analytics
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  python-service:
    build: ./python-service
    ports:
      - "8000:8000"
    environment:
      - PYTHON_SERVICE_URL=http://localhost:8000
    volumes:
      - ./python-service:/app

volumes:
  mysql_data:
